version: "3"
services:
  backend:
    image: docker.pkg.github.com/y-kimura-opst/grav-sample/grav:main
    command: sh bin/dev_run.sh
    volumes:
      - ./grav/user:/var/www/grav/_user
    networks:
      - "common"
  frontend:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports: ["80:80"]
    depends_on: ["backend"]
    networks:
      - "common"
networks:
  common:
    driver: bridge