apiVersion: v1
kind: Pod
metadata:
  name: grav-gitsync-test
  namespace: grav
spec:
  containers:
  - image: docker.pkg.github.com/y-kimura-opst/grav-sample/grav:main
    command:
    - php
    - -S
    - 0.0.0.0:8080
    - system/router.php
    imagePullPolicy: Always
    name: sync
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /sync/user
      name: grav-sync
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-n44hs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: github-registry
  initContainers:
  - command:
    - sh
    - -c
    - chown -R 101:82 /sync/user
    image: busybox
    imagePullPolicy: Always
    name: chown
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /sync/user
      name: grav-sync
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-n44hs
      readOnly: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: grav-sync
    persistentVolumeClaim:
      claimName: grav-sync
  - name: default-token-n44hs
    secret:
      defaultMode: 420
      secretName: default-token-n44hs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-18T02:58:49Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-18T02:59:13Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-18T02:59:13Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-18T02:58:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://10b9fa0f93f467d98d637fd67d59376045629e36cff5c34381d73429f3fb971e
    image: docker.pkg.github.com/y-kimura-opst/grav-sample/grav:gitsyncplugin
    imageID: docker-pullable://docker.pkg.github.com/y-kimura-opst/grav-sample/grav@sha256:f4b3d39d7b58f28cc505070929650fecee99fb33c10e3642d5002805c2dc0250
    lastState: {}
    name: sync
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://10b9fa0f93f467d98d637fd67d59376045629e36cff5c34381d73429f3fb971e
        exitCode: 0
        finishedAt: "2021-01-18T02:59:13Z"
        reason: Completed
        startedAt: "2021-01-18T02:59:12Z"
  hostIP: 192.168.65.3
  initContainerStatuses:
  - containerID: docker://55b2f1009ad9573e1301fc5dc37d1f3c5b2eb2366f5b1a3d4e79d0a125522dd1
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f
    lastState: {}
    name: chown
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://55b2f1009ad9573e1301fc5dc37d1f3c5b2eb2366f5b1a3d4e79d0a125522dd1
        exitCode: 0
        finishedAt: "2021-01-18T02:58:48Z"
        reason: Completed
        startedAt: "2021-01-18T02:58:48Z"
  phase: Succeeded
  podIP: 10.1.0.137
  podIPs:
  - ip: 10.1.0.137
  qosClass: BestEffort
  startTime: "2021-01-18T02:58:45Z"
